.\" Manpage for find_suid.
.\" Contact marshall@i.code.pwnz.org to report bugs.
.TH man 1 "9 September" "1.8" "find_suid man page"
.SH NAME
find_suid \- finds suid programs in specified directories.
.SH SYNOPSIS
find_suid /sbin/
.SH DESCRIPTION
Part of the ansvif suite, find_suid will search directories listed on the command line for suid files. Basically a massively simplified "find" command.
.SH OPTIONS
.B /sbin/ /bin/ /usr/sbin/ /usr/bin/ /usr/local/bin/
These should be directories to search.

.SH EXAMPLES
find_suid /usr/sbin/ /usr/bin/
.SH SEE ALSO
find(1), ansvif(1)
.SH BUGS
Probably many.  Fuzz them out.
.SH AUTHOR
Marshall Whittaker / oxagast (marshall@i.code.pwnz.org)
